import type { Option } from "./types";

// Common-first, then alphabetical. Enough coverage for UK / US / CA / IE
// audiences plus the rest of the world.
const NAMES = [
  "United Kingdom",
  "United States",
  "Canada",
  "Ireland",
  "Australia",
  "New Zealand",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Argentina",
  "Austria",
  "Bangladesh",
  "Belgium",
  "Brazil",
  "Bulgaria",
  "Chile",
  "China",
  "Colombia",
  "Croatia",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Egypt",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Ghana",
  "Greece",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Israel",
  "Italy",
  "Japan",
  "Kenya",
  "Latvia",
  "Lithuania",
  "Luxembourg",
  "Malaysia",
  "Malta",
  "Mexico",
  "Morocco",
  "Netherlands",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Saudi Arabia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Thailand",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "Vietnam",
  "Other",
];

export const COUNTRY_OPTIONS: Option[] = NAMES.map((name) => ({
  value: name.toLowerCase().replace(/[^a-z]+/g, "-"),
  label: name,
}));
