import type { Option, OnboardingSchema, Section } from "./types";
import { COUNTRY_OPTIONS } from "./countries";
import { GALLERIES } from "./galleries";

// --- small builders -------------------------------------------------------

const slug = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const opt = (value: string, label: string): Option => ({ value, label });
/** Build options from labels, auto-slugging the value. */
const opts = (...labels: string[]): Option[] =>
  labels.map((l) => ({ value: slug(l), label: l }));

const IMG = (file: string) => `/image/image/${file}`;
/** Logos under `public/brand-img/` (e.g. `/brand-img/GoDaddy-Logo.png`). */
const BRAND_IMG = (file: string) => `/brand-img/${file}`;
/** Label + image under `public/image/image/` (value auto-slugged from label). */
const optImg = (label: string, file: string): Option => ({
  value: slug(label),
  label,
  imageUrl: IMG(file),
});
/** Domain provider option with logo from `public/brand-img/`. */
const domainBrand = (value: string, label: string, file: string): Option => ({
  value,
  label,
  imageUrl: BRAND_IMG(file),
});
/** Job / quoting software option with logo (`value` = slug of `label`). */
const jobSoftwareImg = (label: string, file: string): Option => ({
  value: slug(label),
  label,
  imageUrl: BRAND_IMG(file),
});

const YES_NO = opts("Yes", "No");
const YES_NO_NA = opts("Yes", "No", "Not Applicable");

/** Public template for “Product Sheet”; override via env in deployment. */
const GOOGLE_SHEET_TEMPLATE_URL =
  (typeof process !== "undefined" && process.env.NEXT_PUBLIC_GOOGLE_SHEET_TEMPLATE_URL) ||
  "https://docs.google.com/spreadsheets/d/1vKhwRehisQVFUruX-SXHlZd7FpuF6-Bsa6RDvbtuFDo/edit?gid=1401709806#gid=1401709806";

const GOOGLE_FONTS_URL = "https://fonts.google.com/";

// --- sections -------------------------------------------------------------

const company: Section = {
  id: "company",
  number: 1,
  title: "Company Information",
  subtitle: "Basic details about your company",
  kind: "questions",
  welcomeIntro: {
    heading: "WE BUILD TRADES CLIENT QUESTIONNAIRE & INITIAL SETUP",
    body: "Please complete the following questionnaire with as much detail as possible. Once complete, you will be able to schedule your kick-off meeting with your account manager.\n\nYou can also save your progress by clicking the save button in the bottom right corner of the screen so you don't have to get through it all in one go.",
  },
  heading: "Company Information",
  questions: [
    {
      id: "company_details",
      type: "field-group",
      icon: "building",
      title: "What is your company name & contact details?",
      group: [
        { id: "company_name", type: "text", title: "Company name", required: true, width: "half" },
        {
          id: "business_email",
          type: "email",
          title: "Business email",
          required: true,
          width: "half",
        },
        { id: "phone_number", type: "tel", title: "Phone number", required: true, width: "half" },
        { id: "company_landline", type: "tel", title: "Company landline no.", width: "half" },
        {
          id: "org_type",
          type: "select",
          title: "Company / organisation type",
          required: true,
          width: "half",
          options: [
            opt("ltd", "Limited Company (LTD)"),
            opt("plc", "Public Limited Company (PLC)"),
            opt("llp", "Limited Liability Partnership (LLP)"),
            opt("sole-proprietorship", "Sole Proprietorship"),
            opt("partnership", "Partnership"),
            opt("nonprofit", "Nonprofit Organization"),
            opt("cooperative", "Cooperative"),
            opt("charity", "Charity"),
          ],
        },
        {
          id: "company_registration_number",
          type: "text",
          title: "Company registration number",
          required: true,
          width: "half",
          inputPrefix: "#",
          visibleIf: { all: [{ questionId: "org_type", isAnswered: true }] },
          labelBySibling: {
            siblingId: "org_type",
            rules: [
              {
                when: { oneOf: ["ltd", "plc"] },
                title: "Company Registration Number",
                placeholder: "Company Registration Number",
              },
              {
                when: { equals: "llp" },
                title: "Articles of Organization",
                placeholder: "Articles of Organization",
              },
              {
                when: { equals: "sole-proprietorship" },
                title: "Personal Identification",
                placeholder: "Personal Identification",
              },
              {
                when: { equals: "partnership" },
                title: "Partnership Agreement",
                placeholder: "Partnership Agreement",
              },
              {
                when: { equals: "nonprofit" },
                title: "Employer Identification Number (EIN)",
                placeholder: "Employer Identification Number (EIN)",
              },
              {
                when: { equals: "cooperative" },
                title: "Cooperative Registration Number",
                placeholder: "Cooperative Registration Number",
              },
              {
                when: { equals: "charity" },
                title: "Charity Registration Number",
                placeholder: "Charity Registration Number",
              },
            ],
            default: {
              title: "Company registration number",
              placeholder: "Company registration number",
            },
          },
        },
        {
          id: "tax_identification_number",
          type: "text",
          title: "Tax identification number",
          required: true,
        },
      ],
    },
    {
      id: "your_name",
      type: "field-group",
      icon: "user",
      title: "Enter your name",
      group: [
        { id: "first_name", type: "text", title: "First name", required: true, width: "half" },
        { id: "last_name", type: "text", title: "Last name", required: true, width: "half" },
      ],
    },
    {
      id: "business_proof_of_address",
      type: "file",
      icon: "upload",
      title: "Upload business proof of address",
      helper: "A recent utility bill, bank statement or council document showing your business address.",
    },
    {
      id: "company_address",
      type: "field-group",
      icon: "pin",
      title: "Enter your company address details",
      group: [
        { id: "street_address", type: "text", title: "Street address", required: true },
        { id: "city", type: "text", title: "City", required: true, width: "half" },
        { id: "country", type: "select", title: "Country", required: true, width: "half", options: COUNTRY_OPTIONS },
        { id: "state_region", type: "text", title: "State / region", width: "half" },
        { id: "postal_code", type: "text", title: "Postal code", required: true, width: "half" },
      ],
    },
    {
      id: "company_started_year",
      type: "year-select",
      icon: "calendar",
      title: "What year was the company started?",
      required: true,
      yearRange: { from: 1999, to: 2026 },
    },
    {
      id: "has_partners",
      type: "single-choice",
      icon: "users",
      title: "Will we be discussing this project with any other colleagues or business partners?",
      required: true,
      options: YES_NO,
    },
    {
      id: "partners",
      type: "repeatable-group",
      icon: "users",
      title: "Please provide colleagues' or business partners' details",
      groupItemLabel: "Partner",
      minItems: 1,
      visibleIf: { all: [{ questionId: "has_partners", equals: "yes" }] },
      group: [
        { id: "first_name", type: "text", title: "First name", required: true, width: "half" },
        { id: "last_name", type: "text", title: "Last name", required: true, width: "half" },
        { id: "email", type: "email", title: "Email", required: true, width: "half" },
        { id: "phone", type: "tel", title: "Phone number", required: true, width: "half" },
      ],
      provideLater: {},
    },
    {
      id: "employee_count",
      type: "single-choice",
      icon: "users",
      title: "How many employees, including yourself, work for the business?",
      required: true,
      options: [
        opt("1", "1"),
        opt("2-5", "2 to 5"),
        opt("6-10", "6 to 10"),
        opt("11-20", "11 to 20"),
        opt("20-50", "20 to 50"),
        opt("50-plus", "50+"),
      ],
    },
    {
      id: "van_count",
      type: "single-choice",
      icon: "truck",
      title: "How many vans do you currently have on the road?",
      required: true,
      options: [
        opt("1-4", "1 to 4"),
        opt("5-9", "5 to 9"),
        opt("10-plus", "10+"),
        opt("not-applicable", "Not Applicable"),
      ],
    },
    {
      id: "van_picture",
      type: "file",
      fileUpload: { mode: "image", maxSizeMB: 8 },
      icon: "upload",
      title: "Do you have a real picture of your vans you can upload?",
      visibleIf: { all: [{ questionId: "van_count", oneOf: ["1-4", "5-9", "10-plus"] }] },
    },
    {
      id: "emergency_24_7",
      type: "single-choice",
      icon: "clock",
      title: "Are you available for 24/7 emergency services?",
      required: true,
      options: YES_NO_NA,
    },
    {
      id: "finance_options",
      type: "single-choice",
      icon: "card",
      title: "Do you provide finance options to your customers?",
      required: true,
      options: opts("Yes", "Not Applicable"),
    },
    {
      id: "finance_company_name",
      type: "textarea",
      icon: "card",
      title: "Please provide the name of the finance company and any additional information if necessary",
      visibleIf: { all: [{ questionId: "finance_options", equals: "yes" }] },
    },
    {
      id: "business_scope",
      type: "single-choice",
      icon: "globe",
      title: "Does your business operate Nationally or Locally?",
      required: true,
      options: opts("Nationally", "Locally"),
    },
    {
      id: "mile_radius",
      type: "single-choice",
      icon: "pin",
      title: "What mile radius do you IDEALLY want to be covering?",
      visibleIf: { all: [{ questionId: "business_scope", equals: "locally" }] },
      options: [
        opt("5", "5 miles"),
        opt("10", "10 miles"),
        opt("15", "15 miles"),
        opt("20", "20 miles"),
        opt("25", "25 miles"),
        opt("30", "30 miles"),
        opt("35", "35 miles"),
        opt("40", "40 miles"),
        opt("45", "45 miles"),
        opt("50-plus", "50+ miles"),
      ],
    },
    {
      id: "top_10_towns",
      type: "textarea",
      icon: "pin",
      title: "List the names of the top 10 towns / cities you want your business to target, in order of priority",
      rows: 6,
      visibleIf: { all: [{ questionId: "mile_radius", isAnswered: true }] },
    },
    {
      id: "opening_hours",
      type: "time-range",
      icon: "clock",
      title: "What are the opening hours for the business?",
      required: true,
    },
    {
      id: "competitor_advantages",
      type: "repeatable-group",
      icon: "star",
      title:
        "Please write a detailed list below of what makes your business better than your competitors and why customers should choose you over them.",
      helper: "Add as many points as you like.",
      groupItemLabel: "Reason",
      minItems: 1,
      group: [
        { id: "reason", type: "text", title: "Reason", required: true },
        { id: "description", type: "text", title: "Description", required: true },
      ],
    },
  ],
};

const branding: Section = {
  id: "branding",
  number: 2,
  title: "Website Design & Branding",
  subtitle: "Your logo, look, and content",
  kind: "questions",
  heading: "Website Design & Branding",
  transitionIntro: {
    title: "Website Design And Branding",
    description:
      "Congratulations on completing the first section of your onboarding questionnaire. We're now going to move onto the website design section.\n\nWe will be collecting information on the following and this will help the design team get a clear vision of what you want to create:",
    checklist: [
      "Website Logo",
      "Mockup Ideas",
      "Color Palette",
      "Fonts",
      "Design Preferences",
      "Social Media URLs",
      "Ideas And Inspirations",
    ],
    imageSrc: "/design-web.png",
    imageAlt: "Website design and branding illustration",
    nextLabel: "NEXT",
  },
  questions: [
    {
      id: "logo_situation",
      type: "single-choice",
      icon: "image",
      title: "Please select the option below that is most relevant",
      required: true,
      options: [
        opt("keep", "I have a logo and would like to keep it as it is"),
        opt("new", "I have a logo but would like you to create a new version"),
        opt("none", "I do not currently have a logo"),
      ],
    },
    {
      id: "logo_upload_keep",
      type: "file",
      fileUpload: { mode: "image", maxSizeMB: 8 },
      icon: "upload",
      title: "Please upload the company logo you want us to make the changes to",
      visibleIf: { all: [{ questionId: "logo_situation", equals: "keep" }] },
      provideLater: {},
    },
    {
      id: "logo_upload_new",
      type: "file",
      fileUpload: { mode: "image", maxSizeMB: 8 },
      icon: "upload",
      title: "Please upload the company logo you would like displayed on your website",
      visibleIf: { all: [{ questionId: "logo_situation", equals: "new" }] },
      provideLater: {},
    },
    {
      id: "logo_new_description",
      type: "textarea",
      icon: "image",
      title: "Can you tell us more about what you want to change in your logo?",
      visibleIf: { all: [{ questionId: "logo_situation", equals: "new" }] },
    },
    {
      id: "logo_style_pick",
      type: "image-gallery-pick",
      icon: "image",
      title: "Please select the style of logo you like the look of",
      galleryKey: "logo-styles",
      galleryOptions: GALLERIES["logo-styles"],
      galleryMulti: true,
      visibleIf: { all: [{ questionId: "logo_situation", equals: "none" }] },
    },
    {
      id: "logo_style_description",
      type: "textarea",
      icon: "image",
      title: "Any details about the logo style you'd like?",
      visibleIf: { all: [{ questionId: "logo_situation", equals: "none" }] },
    },
    {
      id: "branding_style",
      type: "single-choice",
      icon: "palette",
      title: "For your brand we can create different styles of design. Please select whether you would like your branding to be based on real life, animated or a mixture of both.",
      helper: "Please note that once you choose a design style, it cannot be changed.",
      required: true,
      options: opts("Real", "Animated", "Mixed"),
    },
    {
      id: "template_real",
      type: "image-gallery-pick",
      icon: "image",
      title: "Browse the designs and select the template you like the most (Real). We'll use it as inspiration.",
      required: true,
      galleryKey: "templates-real",
      galleryOptions: GALLERIES["templates-real"],
      galleryUploadCompanionKey: "template_real_upload",
      visibleIf: { all: [{ questionId: "branding_style", equals: "real" }] },
    },
    {
      id: "template_real_upload",
      type: "file",
      icon: "upload",
      title: "Upload your design reference",
      required: true,
      fileUpload: { mode: "image", maxSizeMB: 10 },
      visibleIf: { all: [{ questionId: "template_real", equals: "upload-my-own" }] },
    },
    {
      id: "template_animated",
      type: "image-gallery-pick",
      icon: "image",
      title: "Browse the designs and select the template you like the most (Animated). We'll use it as inspiration.",
      required: true,
      galleryKey: "templates-animated",
      galleryOptions: GALLERIES["templates-animated"],
      galleryUploadCompanionKey: "template_animated_upload",
      visibleIf: { all: [{ questionId: "branding_style", equals: "animated" }] },
    },
    {
      id: "template_animated_upload",
      type: "file",
      icon: "upload",
      title: "Upload your design reference",
      required: true,
      fileUpload: { mode: "image", maxSizeMB: 10 },
      visibleIf: { all: [{ questionId: "template_animated", equals: "upload-my-own" }] },
    },
    {
      id: "template_mixed",
      type: "image-gallery-pick",
      icon: "image",
      title: "Browse the designs and select the template you like the most (Mixed). We'll use it as inspiration.",
      required: true,
      galleryKey: "templates-mixed",
      galleryOptions: GALLERIES["templates-mixed"],
      galleryUploadCompanionKey: "template_mixed_upload",
      visibleIf: { all: [{ questionId: "branding_style", equals: "mixed" }] },
    },
    {
      id: "template_mixed_upload",
      type: "file",
      icon: "upload",
      title: "Upload your design reference",
      required: true,
      fileUpload: { mode: "image", maxSizeMB: 10 },
      visibleIf: { all: [{ questionId: "template_mixed", equals: "upload-my-own" }] },
    },
    {
      id: "template_feedback",
      type: "textarea",
      icon: "image",
      title: "What do you like or dislike about the mockup / template you chose?",
      helper: "(You can click the back button below to review the design without losing your input).",
      rows: 5,
    },
    {
      id: "affiliated_website",
      type: "single-choice",
      icon: "link",
      title: "Do you have any other website that needs to be connected or affiliated with your new one?",
      required: true,
      options: YES_NO,
    },
    {
      id: "affiliated_website_url",
      type: "url",
      icon: "link",
      title: "Enter Website Name or URL",
      visibleIf: { all: [{ questionId: "affiliated_website", equals: "yes" }] },
    },
    {
      id: "industry",
      type: "multi-choice",
      icon: "briefcase",
      title: "What industry is your business in?",
      helper: "Select all that apply.",
      required: true,
      options: [
        optImg("Plumbing", "plumbing.svg"),
        optImg("HVAC", "hvac.svg"),
        optImg("Electrical", "electrical.svg"),
        optImg("Roofing", "roofing.svg"),
        optImg("Moving Services", "van.svg"),
        optImg("Landscaping", "Landscaping.svg"),
        optImg("Restoration Services", "Retoration.svg"),
        optImg("Insulation Services", "insulation.svg"),
        optImg("Security Services", "security.svg"),
        optImg("ECO4 Services", "eco4.svg"),
        optImg("Other", "other.svg"),
      ],
    },
    {
      id: "industry_other",
      type: "text",
      icon: "briefcase",
      title: "Please tell us your industry",
      visibleIf: { all: [{ questionId: "industry", includes: "other" }] },
    },
    {
      id: "brands_manufacturers",
      type: "textarea",
      icon: "tag",
      title: "List the brands and manufacturers you work with and want to display on your website",
      rows: 5,
    },
    {
      id: "accreditations",
      type: "textarea",
      icon: "award",
      title: "List the accreditations and certificates you'd like to display on your website",
      rows: 5,
    },
    {
      id: "website_services",
      type: "multi-choice",
      icon: "wrench",
      title: "Which services would you like to include on your new website? Start with your main service.",
      required: true,
      options: [
        optImg("Boiler & Heating Services", "boiler.svg"),
        optImg("Solar Energy Services", "solar-panel.svg"),
        optImg("EV Charger Services", "electric-car.svg"),
        optImg("Cooling & HVAC Services", "hvac.svg"),
        optImg("Heat Pump Services", "insulation.svg"),
        optImg("Other", "other.svg"),
      ],
    },
    {
      id: "website_services_other",
      type: "text",
      icon: "wrench",
      title: "Please tell us the service",
      visibleIf: { all: [{ questionId: "website_services", includes: "other" }] },
    },
    {
      id: "google_sheet_url",
      type: "url",
      icon: "sheet",
      presentation: "google-sheet-dark",
      title: "Copy the Google sheet, Add Your Products, and Submit the URL Here.",
      helper:
        "Click the button below to open the Google Sheets product template. Copy it to your drive, add your products, and then submit the sheet URL below.",
      placeholder: "Please Enter Google Sheet URL",
      googleSheetResources: {
        templateUrl: GOOGLE_SHEET_TEMPLATE_URL,
        tutorialVideoUrl:
          "https://www.loom.com/share/dc3757991d6d4bcfaca750a9a8e0159d?sid=d5ae35cb-0894-4d06-830e-5fc7643e2720",
        tutorialLinkLabel: "Click here to watch a video tutorial on how to add a product to the sheet.",
        productSheetButtonLabel: "Product Sheet",
      },
      provideLater: {},
    },
    {
      id: "offers",
      type: "repeatable-group",
      icon: "tag",
      title: "List any offers you're willing to use in your advertising",
      groupItemLabel: "Offer",
      group: [
        { id: "offer", type: "text", title: "Offer", required: true },
        { id: "description", type: "textarea", title: "Description" },
      ],
      provideLater: {},
    },
    {
      id: "typography_choice",
      type: "single-choice",
      icon: "type",
      title: "In order to maintain a consistent brand image, please choose one of the typography options below",
      required: true,
      options: [
        opt("current", "Please use the current fonts we are using on our existing website"),
        opt("browse", "We would like to browse new font options for our website"),
      ],
    },
    {
      id: "current_fonts_description",
      type: "textarea",
      icon: "type",
      title: "Please provide a link to the website or write the name of the font",
      helper: "Please enter website url or font name.",
      placeholder: "Write here",
      rows: 5,
      required: true,
      visibleIf: { all: [{ questionId: "typography_choice", equals: "current" }] },
    },
    {
      id: "heading_font",
      type: "single-choice",
      icon: "type",
      title: "Please select the HEADING font you like the most",
      required: true,
      otherTextAnswerId: "heading_font_other",
      visibleIf: { all: [{ questionId: "typography_choice", equals: "browse" }] },
      options: [
        opt("roboto", "Roboto"),
        opt("oswald", "Oswald"),
        opt("poppins", "Poppins"),
        opt("montserrat", "Montserrat"),
        opt("lato", "Lato"),
        { value: "other", label: "Other", linkUrl: GOOGLE_FONTS_URL },
      ],
    },
    {
      id: "heading_font_other",
      type: "text",
      icon: "type",
      title: "Enter Google Font Name",
      placeholder: "Enter Font Name",
      visibleIf: { all: [{ questionId: "heading_font", equals: "other" }] },
    },
    {
      id: "paragraph_font",
      type: "single-choice",
      icon: "type",
      title: "Please select the PARAGRAPH font you like the most",
      required: true,
      otherTextAnswerId: "paragraph_font_other",
      visibleIf: { all: [{ questionId: "heading_font", isAnswered: true }] },
      options: [
        opt("roboto", "Roboto"),
        opt("poppins", "Poppins"),
        opt("montserrat", "Montserrat"),
        opt("lato", "Lato"),
        { value: "other", label: "Other", linkUrl: GOOGLE_FONTS_URL },
      ],
    },
    {
      id: "paragraph_font_other",
      type: "text",
      icon: "type",
      title: "Please tell us the paragraph font",
      placeholder: "Enter Font Name",
      visibleIf: { all: [{ questionId: "paragraph_font", equals: "other" }] },
    },
    {
      id: "colour_preference",
      type: "single-choice",
      icon: "palette",
      title:
        "To maintain consistency in your branding, could you please let us know your preferred colours for the website branding?",
      required: true,
      options: [
        opt("choose-list", "Choose from our list"),
        opt("create-own", "Create your own palette"),
        opt("from-logo", "Use the colours from our logo"),
        opt("from-current-site", "Use the colours from our current website"),
      ],
    },
    {
      id: "colour_palette_pick",
      type: "image-gallery-pick",
      icon: "palette",
      title: "Choose a palette",
      required: true,
      galleryKey: "colour-palettes",
      galleryOptions: GALLERIES["colour-palettes"],
      visibleIf: { all: [{ questionId: "colour_preference", equals: "choose-list" }] },
    },
    {
      id: "colour_palette_description",
      type: "textarea",
      icon: "palette",
      required: true,
      title:
        "Generate palette from here. Check-out how to share the colour palette with us Click here.",
      titleRich: [
        { type: "text", text: "Generate palette from " },
        { type: "link", text: "here", href: "https://coolors.co/palettes/trending" },
        { type: "text", text: ". Check-out how to share the colour palette with us " },
        { type: "link", text: "Click here", href: "https://wbt.vmaker.com/record/XnJeedrRMXvoejoW/" },
        { type: "text", text: "." },
      ],
      helper: "Paste your generated palette link or describe the colours you have in mind.",
      visibleIf: { all: [{ questionId: "colour_preference", equals: "create-own" }] },
    },
    {
      id: "button_style",
      type: "image-gallery-pick",
      icon: "image",
      title: "Please select the style of button you like the most",
      required: true,
      galleryKey: "button-styles",
      galleryOptions: GALLERIES["button-styles"],
      visibleIf: {
        anyOf: [
          { all: [{ questionId: "colour_preference", equals: "from-logo" }] },
          { all: [{ questionId: "colour_preference", equals: "from-current-site" }] },
          {
            all: [
              { questionId: "colour_preference", equals: "choose-list" },
              { questionId: "colour_palette_pick", isAnswered: true },
            ],
          },
          {
            all: [
              { questionId: "colour_preference", equals: "create-own" },
              { questionId: "colour_palette_description", isAnswered: true },
            ],
          },
        ],
      },
    },
    {
      id: "website_features",
      type: "repeatable-group",
      icon: "sparkles",
      title: "Include details of any features you'd like to add to your website / landing page",
      helper:
        "Add one row per feature. Include a URL if it helps explain what you want.\n\nExample:\n[Boiler Quote Form] [https://origin-gph.com/quote/]",
      groupItemLabel: "Feature",
      group: [
        { id: "feature", type: "text", title: "Feature", required: true },
        { id: "url", type: "url", title: "URL (if any)" },
      ],
      provideLater: {},
    },
    {
      id: "tone_of_voice",
      type: "single-choice",
      icon: "type",
      title: "How would you like your website to sound? Below are four tone-of-voice options.",
      required: true,
      singleChoiceColumns: 1,
      options: [
        {
          value: slug("Formal and Professional"),
          label: "Formal and Professional",
          description:
            "Professional, authoritative, and business-focused. Emphasizes expertise and reliability.",
          example:
            "Our team delivers high-quality workmanship backed by industry accreditation. We follow all safety regulations and ensure every project is completed to the highest standard.",
        },
        {
          value: slug("Friendly and Approachable"),
          label: "Friendly and Approachable",
          description: "Warm and easy to understand. Still professional, but more relaxed.",
          example:
            "We're here to make your project as simple and stress-free as possible. Our friendly team is always happy to answer questions and guide you through every step.",
        },
        {
          value: slug("Chatty and Lightly Humorous"),
          label: "Chatty and Lightly Humorous",
          description:
            "Casual, slightly playful. Reflects your personality without sounding unprofessional.",
          warning: "(Not ideal for very serious or compliance-heavy industries.)",
          example:
            "Leaky pipe? Faulty boiler? No worries — we've seen worse! Give us a call and we'll sort it out before it turns into an emergency.",
        },
        {
          value: slug("Sales-Driven, Short and Concise"),
          label: "Sales-Driven, Short and Concise",
          description: "Direct, high-impact language. Focuses on benefits, speed and results.",
          example:
            "Need a new boiler fast? We install high-performance systems with clear pricing and next-day availability. No fuss. No delays.",
        },
      ],
    },
    {
      id: "liked_websites",
      type: "repeatable-group",
      icon: "link",
      title:
        "Please provide the URLs to any other websites that you like and provide a detailed description below.",
      helper:
        "We will use these websites as inspiration for your project.\n\nExample:\n[https://gastekhomeassist.co.uk/] [I really like how the background of the main section]",
      groupItemLabel: "Website",
      repeatableAddButtonLabel: "Add more",
      group: [
        {
          id: "website_url",
          type: "url",
          title: "Website URL",
          required: true,
          width: "half",
          placeholder: "Website url*",
        },
        {
          id: "what_you_like",
          type: "textarea",
          title: "What do you like about this website?",
          required: true,
          width: "half",
          placeholder: "What do you like about this website?*",
          rows: 4,
        },
      ],
      provideLater: {},
    },
    {
      id: "social_media",
      type: "field-group",
      icon: "share",
      title: "Add your current social media URLs in the relevant boxes",
      helper: "Add at least one social profile URL — you do not need to fill every box.",
      fieldGroupMinFilled: 1,
      group: [
        {
          id: "facebook",
          type: "url",
          title: "Facebook",
          width: "half",
          labelIconUrl: IMG("facebook.svg"),
        },
        {
          id: "instagram",
          type: "url",
          title: "Instagram",
          width: "half",
          labelIconUrl: IMG("instagram.svg"),
        },
        {
          id: "twitter",
          type: "url",
          title: "Twitter / X",
          width: "half",
          labelIconUrl: IMG("twitter-sign.svg"),
        },
        {
          id: "linkedin",
          type: "url",
          title: "LinkedIn",
          width: "half",
          labelIconUrl: IMG("linkedin.svg"),
        },
        {
          id: "tiktok",
          type: "url",
          title: "TikTok",
          width: "half",
          labelIconUrl: IMG("tiktok.svg"),
        },
        {
          id: "youtube",
          type: "url",
          title: "YouTube",
          width: "half",
          labelIconUrl: IMG("youtube.svg"),
        },
      ],
    },
    {
      id: "has_reviews",
      type: "single-choice",
      icon: "star",
      title: "Do you have reviews from any past customers on other websites?",
      required: true,
      options: YES_NO,
    },
    {
      id: "review_urls",
      type: "repeatable-group",
      icon: "star",
      title: "Provide the links (URLs) to any website where you have customer reviews",
      groupItemLabel: "Review link",
      minItems: 1,
      visibleIf: { all: [{ questionId: "has_reviews", equals: "yes" }] },
      group: [{ id: "url", type: "url", title: "URL", required: true }],
    },
    {
      id: "display_email",
      type: "email",
      icon: "mail",
      title: "What email address do you want to display on your website?",
      helper:
        "This address will receive your lead notifications.\n\nNote: We recommend using a professional email such as info@yourbusinessname.com. If you do not have this yet, please select \"I will provide later\" as we will prompt you to create this during milestone 1.",
      placeholder: "Email Address",
      required: true,
      provideLater: {},
    },
  ],
};

const ads: Section = {
  id: "ads",
  number: 3,
  title: "Ads Information",
  subtitle: "Your customers, keywords and ad history",
  kind: "questions",
  heading: "Ads Information",
  transitionIntro: {
    title: "Ads Information",
    description:
      "Great job on finishing the second part! Now, let's move on to some of the Ads related questions. Your insights will help us create a tailored advertising strategy that aligns perfectly with your goals and values. We will be collecting information on:",
    checklist: [
      "Advertising Objectives",
      "Target Audience",
      "Content Ideas",
      "Preferred Platforms",
      "Specific URLs",
      "Insights",
    ],
    closingText:
      "If you have any specific ideas or inspiration regarding your ad campaigns, please share them with us. Your input matters.",
    imageSrc: "/ads-intro.png",
    imageAlt: "Social media and advertising illustration with megaphone and phone",
    nextLabel: "NEXT",
  },
  questions: [
    {
      id: "customer_age",
      type: "single-choice",
      icon: "user",
      title: "What is the average age of a typical customer?",
      required: true,
      options: opts("18 - 24", "25 - 34", "35 - 44", "45 - 54", "55 - 64", "65+"),
    },
    {
      id: "top_keywords_status",
      type: "single-choice",
      icon: "search",
      title:
        "If you had a magic wand and could appear at the top of Google for any keywords, what would the top 5 keywords / phrases be?",
      helper: "(Please add as many as you feel would be relevant)",
      required: true,
      options: [opt("list", "I'll list them"), opt("not-sure", "Not Sure")],
    },
    {
      id: "top_keywords",
      type: "textarea",
      icon: "search",
      title: "Your top 5 keywords / phrases",
      placeholder: "Write keywords here",
      rows: 5,
      required: true,
      visibleIf: { all: [{ questionId: "top_keywords_status", equals: "list" }] },
    },
    {
      id: "customer_lifetime_value",
      type: "single-choice",
      icon: "card",
      title: "What is the average customer / client worth to you over their lifetime? (£)",
      required: true,
      options: [
        opt("1000", "£1000"),
        opt("2000", "£2000"),
        opt("3000", "£3000"),
        opt("4000", "£4000"),
        opt("5000", "£5000"),
        opt("6000", "£6000"),
        opt("7000", "£7000"),
        opt("8000", "£8000"),
        opt("9000", "£9000"),
        opt("10000-plus", "£10000+"),
      ],
    },
    {
      id: "lead_conversion_rate",
      type: "single-choice",
      icon: "trend",
      title: "What percentage of leads does your team convert into sales?",
      required: true,
      options: [
        opt("lt-10", "Less than 10%"),
        opt("10", "10%"),
        opt("20-40", "20 - 40%"),
        opt("40-60", "40 - 60%"),
        opt("60-80", "60 - 80%"),
        opt("gt-80", "More than 80%"),
        opt("not-sure", "Not sure"),
      ],
    },
    {
      id: "additional_leads_per_week",
      type: "textarea",
      icon: "trend",
      title: "Realistically, how many additional leads would you like to be bringing in each week?",
      rows: 3,
    },
    {
      id: "tried_google_ads",
      type: "single-choice",
      icon: "search",
      title: "Have you tried Google Ads before?",
      required: true,
      options: YES_NO,
    },
    {
      id: "google_ads_details",
      type: "textarea",
      icon: "search",
      title: "Provide details of the last Google Ads campaign you ran and your thoughts on its performance",
      rows: 5,
      visibleIf: { all: [{ questionId: "tried_google_ads", equals: "yes" }] },
    },
    {
      id: "sales_process_google",
      type: "textarea",
      icon: "flow",
      title: "Do your best to describe & map out your sales process, including the names of the people involved. In other words once you get a new lead/enquiry please describe the process in which you turn that lead into a customer. The more details we have here the better",
      rows: 6,
    },
    {
      id: "tried_facebook_ads",
      type: "single-choice",
      icon: "share",
      title: "Have you tried Facebook Ads before?",
      required: true,
      options: YES_NO,
    },
    {
      id: "facebook_ads_details",
      type: "textarea",
      icon: "share",
      title: "Provide details of the last Facebook Ads campaign you ran and your thoughts on its performance",
      rows: 5,
      visibleIf: { all: [{ questionId: "tried_facebook_ads", equals: "yes" }] },
    },
    {
      id: "sales_process_facebook",
      type: "textarea",
      icon: "flow",
      title: "Describe and map out your sales process (again), including the names of the people involvedDo your best to describe & map out your sales process, including the names of the people involved. In other words once you get a new lead/enquiry please describe the process in which you turn that lead into a customer. The more details we have here the better.",
      rows: 6,
    },
  ],
};

const PROVIDERS_NEED_CREDENTIALS = [
  "hostgator",
  "bluehost",
  "register-com",
  "domain-com",
  "dreamhost",
  "name-com",
  "namecheap",
  "namesilo",
  "yahoo-mail",
  "wix-com",
  "ipage",
  "network-solution",
  "other",
];

const access: Section = {
  id: "access",
  number: 4,
  title: "Account Access Information",
  subtitle: "Domains, hosting and payments",
  kind: "questions",
  heading: "Account Access Information",
  transitionIntro: {
    title: "Account Access Information",
    description:
      "We're nearly there! Great job on getting this far and providing us with the necessary information for us to become a valuable asset to your business.\n\nWe now just need the account access information that will help us connect payments, third-party job management systems, and make it easy to transfer the new website when it is ready.\n\nWe will be collecting information on:",
    checklist: ["Domain", "CRM Software", "Stripe", "Website"],
    imageSrc: "/account-access-hero.svg",
    imageAlt: "Secure access: padlock and smartphone with account icons",
    nextLabel: "NEXT",
  },
  questions: [
    {
      id: "has_current_website",
      type: "single-choice",
      icon: "globe",
      title: "Do you have a current website you are running at the moment?",
      required: true,
      options: YES_NO,
    },
    {
      id: "current_website_domain",
      type: "url",
      icon: "link",
      title: "Can you provide the current website's domain name (URL)?",
      visibleIf: { all: [{ questionId: "has_current_website", equals: "yes" }] },
    },
    {
      id: "host_new_on_current_domain",
      type: "single-choice",
      icon: "globe",
      title: "Is this the domain you'd like to use to host the new website / landing page we'll be creating?",
      visibleIf: { all: [{ questionId: "has_current_website", equals: "yes" }] },
      options: YES_NO,
    },
    {
      id: "has_other_affiliated_website",
      type: "single-choice",
      icon: "link",
      title: "Do you have any other website that needs to be connected or affiliated with your new one?",
      visibleIf: { all: [{ questionId: "has_current_website", equals: "yes" }] },
      options: YES_NO,
    },
    {
      id: "other_affiliated_domain",
      type: "url",
      icon: "link",
      title: "Can you provide the other website's domain name (URL)?",
      visibleIf: { all: [{ questionId: "has_other_affiliated_website", equals: "yes" }] },
    },
    {
      id: "domain_managed_by_company",
      type: "single-choice",
      icon: "users",
      title: "Do you have any company managing your domain, email and hosting for you?",
      visibleIf: { all: [{ questionId: "has_current_website", equals: "yes" }] },
      options: YES_NO,
    },
    {
      id: "domain_manager_contact",
      type: "field-group",
      icon: "user",
      title: "Provide the name and email of the contact person who manages your website, domain and email",
      visibleIf: { all: [{ questionId: "domain_managed_by_company", equals: "yes" }] },
      group: [
        { id: "person_name", type: "text", title: "Person name", required: true, width: "half" },
        { id: "person_email", type: "email", title: "Person email", required: true, width: "half" },
      ],
    },
    {
      id: "desired_domain_name",
      type: "textarea",
      icon: "link",
      title:
        "Please type the domain name that you would like us to use for the new website/landing page we will be creating.",
      helperRich: [
        { type: "text", text: "(If you do not have the domain, please " },
        {
          type: "link",
          text: "click here",
          href: "https://www.loom.com/share/6d7107a38a244e8cb514507be961dc63?t=12",
          openInModal: true,
        },
        {
          type: "text",
          text: " to watch this short video on how to purchase a domain using GoDaddy and add the domain before moving on).",
        },
      ],
      placeholder: "Write Here",
      rows: 3,
      visibleIf: {
        any: [
          { questionId: "has_current_website", equals: "no" },
          { questionId: "domain_registered", equals: "no" },
        ],
      },
    },
    {
      id: "domain_registered",
      type: "single-choice",
      icon: "globe",
      title: "Have you registered your domain / hosting?",
      required: true,
      options: YES_NO,
    },
    {
      id: "domain_provider",
      type: "single-choice",
      icon: "globe",
      title: "Please select your domain provider",
      singleChoiceColumns: 2,
      visibleIf: { all: [{ questionId: "domain_registered", equals: "yes" }] },
      options: [
        domainBrand("godaddy", "GoDaddy", "GoDaddy-Logo.png"),
        domainBrand("hostgator", "HostGator", "HostGator.png"),
        domainBrand("bluehost", "Bluehost", "Bluehost.png"),
        domainBrand("register-com", "Register.com", "register.com_.png"),
        domainBrand("domain-com", "Domain.com", "Domain.com_.png"),
        domainBrand("dreamhost", "DreamHost", "dreamhost.png"),
        domainBrand("name-com", "Name.com", "Name.com-Logo.png"),
        domainBrand("namecheap", "Namecheap", "Namecheap.png"),
        domainBrand("namesilo", "NameSilo", "namesilo.png"),
        domainBrand("yahoo-mail", "Yahoo Mail", "yahoo-mail-logo.png"),
        domainBrand("wix-com", "Wix.com", "Wix.com_.png"),
        domainBrand("ipage", "iPage", "ipage.png"),
        domainBrand("network-solution", "Network Solutions", "network-solutions.png"),
        domainBrand("other", "Other", "Other-Domain.png"),
        domainBrand("not-sure", "Not sure", "Not-Sure.png"),
      ],
    },
    {
      id: "godaddy_delegate_access",
      type: "single-choice",
      icon: "globe",
      title:
        "As you have a Stripe account, we will need developer access to integrate the payment feature into your website/landing page. Please watch the 2-minute tutorial below to see how this is done.",
      helperRich: [
        {
          type: "link",
          text: "Click here to watch the tutorial on how to share access to GoDaddy",
          href: "https://www.loom.com/share/6d7107a38a244e8cb514507be961dc63?t=12",
          openInModal: true,
        },
        {
          type: "text",
          text: "\n\nPlease provide delegate access to your GoDaddy domain account with the following information:\n\nEmail: clientsupport@webuildtrades.com",
        },
      ],
      visibleIf: { all: [{ questionId: "domain_provider", equals: "godaddy" }] },
      options: [opt("yes", "Yes, I have shared the details with you"), opt("no", "No, I will do it later")],
    },
    {
      id: "domain_provider_other_name",
      type: "text",
      icon: "globe",
      title: "Please enter your domain service provider name",
      visibleIf: { all: [{ questionId: "domain_provider", equals: "other" }] },
    },
    {
      id: "domain_provider_credentials",
      type: "field-group",
      icon: "lock",
      title: "Please enter the username and password for your domain provider",
      visibleIf: { all: [{ questionId: "domain_provider", oneOf: PROVIDERS_NEED_CREDENTIALS }] },
      provideLater: {
        label: "I will provide this during the kick-off meeting",
        deferFieldGroupToKickoff: true,
        variant: "dark",
      },
      group: [
        { id: "username", type: "text", title: "Username", required: true, width: "half" },
        { id: "password", type: "password", title: "Password", required: true, width: "half" },
        { id: "notes", type: "textarea", title: "Anything else we should know?" },
      ],
    },
    {
      id: "payment_methods",
      type: "multi-choice",
      icon: "card",
      title: "What forms of payment do you accept?",
      required: true,
      options: [
        optImg("Stripe", "stripe.svg"),
        optImg("Cash", "cash.svg"),
        optImg("Cheque", "cheque.svg"),
        optImg("Bacs", "bacs.svg"),
        optImg("American Express", "american-express.svg"),
        optImg("Mastercard", "mastercard.svg"),
        optImg("Visa", "visa.svg"),
        optImg("Discover", "discover.svg"),
        optImg("Paypal", "paypal-logo.svg"),
      ],
    },
    {
      id: "stripe_developer_access",
      type: "single-choice",
      icon: "card",
      title: "As you have a Stripe account, we need developer access to integrate payments. Have you granted it?",
      helper: "Watch the 2-minute tutorial to see how this is done.",
      visibleIf: {
        all: [
          { questionId: "payment_methods", includes: "stripe" },
          {
            questionId: "payment_methods",
            includesAny: [
              "cash",
              "cheque",
              "bacs",
              "american-express",
              "mastercard",
              "visa",
              "discover",
              "paypal",
            ],
          },
        ],
      },
      options: YES_NO,
    },
    {
      id: "facebook_page_access",
      type: "single-choice",
      icon: "share",
      title:
        "Please provide access of your Facebook page to the following email addresses so that our team can effectively manage and optimise advertising campaigns. If you'd rather handle this later, feel free to skip this step for now.",
      helperRich: [
        {
          type: "link",
          text: "Click here to watch the tutorial on How to share access of Facebook page",
          href: "https://www.loom.com/share/c77ae984a89641b3a24c4c17045baa38?sid=a321fea1-f5af-46b5-859c-2a1c398eaff7",
          openInModal: true,
        },
        {
          type: "text",
          text: "\n\nPlease provide access to the following email addresses for your Facebook page:\n\n• master@webuildtrades.com\n• kul@webuildtrades.com\n• daniel@webuildtrades.com\n• jas@webuildtrades.com\n• dom@webuildtrades.com",
        },
      ],
      options: [opt("yes", "Yes, I have shared the access with you"), opt("no", "No, I will do it later")],
    },
    {
      id: "job_management_software",
      type: "multi-choice",
      icon: "wrench",
      title: "Do you use any of the following quoting or job-management softwares?",
      required: true,
      multiChoiceColumns: 3,
      options: [
        jobSoftwareImg("ServiceM8", "sericem8-icon.png"),
        jobSoftwareImg("Commusoft", "commusoft-icon.png"),
        jobSoftwareImg("Simpro", "simpro-icon.png"),
        jobSoftwareImg("Quotient", "roofing-icon.png"),
        jobSoftwareImg("Proposify", "moving-service-icon.png"),
        jobSoftwareImg("Tradify", "tradify-icon.png"),
        jobSoftwareImg("Better Proposal", "restroration-service-icon.png"),
        jobSoftwareImg("Xero", "home-service-icon.png"),
        jobSoftwareImg("ServiceTitan", "Service-Titan.png"),
        jobSoftwareImg("Housecall Pro", "housecall.png"),
        jobSoftwareImg("Keap (Infusionsoft)", "Keap-Infusionsoft.png"),
        jobSoftwareImg("HubSpot", "Hubspot.png"),
        jobSoftwareImg("Job Logic", "Job-Logic.png"),
        jobSoftwareImg("Other", "other-icon.png"),
      ],
      provideLater: {},
    },
    {
      id: "job_management_software_other",
      type: "text",
      icon: "wrench",
      title: "Please tell us the software",
      visibleIf: { all: [{ questionId: "job_management_software", includes: "other" }] },
    },
    {
      id: "job_software_credentials",
      type: "field-group",
      icon: "lock",
      title: "Please provide access to your job-management software tool",
      visibleIf: { all: [{ questionId: "job_management_software", isAnswered: true }] },
      group: [
        { id: "username", type: "text", title: "Username", width: "half" },
        { id: "password", type: "password", title: "Password", width: "half" },
      ],
    },
  ],
};

const completion: Section = {
  id: "completion",
  number: 5,
  title: "Final Section",
  subtitle: "A quick rating and any feedback",
  kind: "questions",
  heading: "You're all done",
  introBody:
    "Congratulations on completing your onboarding questionnaire. We know it's a lot of information, but it arms us with everything we need about your business from day one. Two last quick questions.",
  questions: [
    {
      id: "satisfaction_rating",
      type: "single-choice",
      icon: "star",
      title: "How would you rate your onboarding experience so far? (1 = poor, 10 = excellent)",
      required: true,
      options: Array.from({ length: 10 }, (_, i) => opt(String(i + 1), String(i + 1))),
    },
    {
      id: "experience_feedback",
      type: "textarea",
      icon: "chat",
      title: "Honest feedback matters to us. How could we have improved your experience, or any thoughts on your journey?",
      rows: 6,
    },
  ],
};

export const ONBOARDING_SCHEMA: OnboardingSchema = {
  sections: [company, branding, ads, access, completion],
  keyFields: {
    email: "company_details.business_email",
    phone: "company_details.phone_number",
    taxId: "company_details.tax_identification_number",
  },
  emailCapturePath: "company_details.business_email",
  satisfactionPath: "satisfaction_rating",
};
